In [1]:
import numpy as np
import math
import scipy.stats as stats
from scipy.linalg import sqrtm
import scipy
import matplotlib.pyplot as plt
import time
import datetime
import random

import numba
from numba import jit, njit
from numba.typed import List

# 1.) functions

In [2]:
def my_rbeta(num_hypo, prob_to_1, mu0, mu1, variance_0, variance_1, with_h = False): 
    
    # Z & vector h
    Z_vec = np.random.normal(0,1,num_hypo)
    vec_h = np.random.binomial(1, p=prob_to_1, size=num_hypo)

    # mu's
    mu_vec_1 = vec_h * mu1 
    mu_vec_1_0 = np.where(mu_vec_1 == 0, mu0, mu_vec_1)

    # variance & std err
    var_vec_1 = vec_h * variance_1
    var_vec_1_0 = np.where(var_vec_1 == 0, variance_0, var_vec_1)
    sqrt_var_vec_1_0 = np.sqrt(var_vec_1_0)
    
    if not with_h:
        return sqrt_var_vec_1_0 * (Z_vec + mu_vec_1_0)
    else:
        return sqrt_var_vec_1_0 * (Z_vec + mu_vec_1_0), vec_h
    

# 2.) Factory

### 2.1.) Study 1# - 1 

- i need to do a MACRO loop all over the p1_ array

In [3]:
%%time
### SETTING: Study 1# - 1.) 1/10

alpha = 0.05

num_hypo = [3000, 1500]
prob_to_1 = [0.3, 0.1]

mu0 = [0, 0]
mu1 = [-2, 4]

variance_0 = [1, 1]
variance_1 = [1, 1]



# Blocks building

simulation_1_1_1_10 = []
block_of_blockbeta = []
block_of_vec_h = []

for i in range(30000): # 30000
    
    # each run is for 2 groups of hypotheses, so we have to have a list of its data locally, and add it to the general iteration
    blockbeta_local_two_groups = []
    vec_h_local_two_groups = []
    
    for i in range(len(mu0)):    
        blockbeta, vec_h = block_beta, vec_h = my_rbeta(num_hypo[i], 
                                     prob_to_1[i], 
                                     mu0[i], 
                                     mu1[i], 
                                     variance_0[i], 
                                     variance_1[i],
                                     True)
        blockbeta_local_two_groups.append(blockbeta)
        vec_h_local_two_groups.append(vec_h)
        
    block_of_blockbeta.append(blockbeta_local_two_groups)
    block_of_vec_h.append(vec_h_local_two_groups)

simulation_1_1_1_10.append(block_of_blockbeta)
simulation_1_1_1_10.append(block_of_vec_h)

#np.save('BLOCK_simulation_1_1_1_10', simulation_1_1_1_10)
#simulation_1_1_1_10

Wall time: 23.2 s


In [5]:
np.save('BLOCK_simulation_1_1_1_10', simulation_1_1_1_10)


C:\Users\ahron\anaconda3\lib\site-packages\numpy\core\_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)


In [7]:
BLOCK_simulation_1_1_1_10_ = np.load('BLOCK_simulation_1_1_1_10.npy', allow_pickle = True)
BLOCK_simulation_1_1_1_10_

array([[[array([-0.22776531, -1.94400873,  0.15629744, ..., -0.31280594,
                 0.6149906 , -3.59109659])                              ,
         array([ 0.31024019, -0.1357289 , -0.62647739, ..., -1.34666477,
                -0.1508148 , -1.15500825])                              ],
        [array([-0.41525232, -2.8390879 , -1.99251977, ..., -0.2304303 ,
                -1.87617448, -1.070783  ])                              ,
         array([-0.40382709,  1.43690603,  0.3132543 , ..., -1.02934071,
                 1.48297296, -0.32239518])                              ],
        [array([-3.41503097, -2.81820511, -0.08565484, ..., -1.48860521,
                -2.06901002, -1.19115514])                              ,
         array([ 1.87015173,  0.70344016, -0.78494309, ...,  1.02705905,
                 1.16007997,  1.14100524])                              ],
        ...,
        [array([ 0.14038805,  1.2938197 ,  0.30864423, ...,  1.83507018,
                -1.6323378 , 

In [10]:
len(BLOCK_simulation_1_1_1_10_[0][0])

2

In [16]:
BLOCK_simulation_1_1_1_10_[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [21]:
ahalan = ['a','b','c']
for letter in ahalan:
    letter = 4
    print(letter)
#a, b, c

4
4
4


NameError: name 'a' is not defined